### PR TITLE
T3149: Change interface reference to $IFNAME

### PR DESCRIPTION
**Pull request by danhusan**

### CODE REVIEW

**Comment by c-po** [comment]
I'm not aware of this substitution variable. Also running `grep -r "IFNAME" /opt/vyatta/share/vyatta-cfg/templates` did not reveal a hit. Is there something not working with `$VAR(../../../@)`?

**Comment by danhusan** [comment]
I found it in multiple other files - and from looking at "gen-interfaces-templates.pl" I assumed that is the new way moving forward. Seems simpler to do it that way.

danhusan@metis:~/vyos/vyatta-cfg-quagga$ grep -r "IFNAME" interface-templates/ | wc -l
68

**Comment by danhusan** [comment]
Oh - you might be looking at a live system? The variable is replaced while building.

**Comment by c-po** [comment]
Ah, that explains a lot, I was indeed running this on a live system.

**Pull request merged**
