### PR TITLE
Fixing IPv6 next-hop in route-map

### PR DESCRIPTION
**Pull request by nicko170**
Quagga is expecting something like:

route-map BGP-TO-OSPFv3 permit 2
 match ipv6 address prefix-list AS123456
 match ipv6 next-hop 2000:1000:1000:4501:1::2

Vyos is generating and trying to use prefix-list / access-list to generate the match ipv6 next-hop statement.

### CODE REVIEW

**Comment by andamasov** [comment]
Hi!
there is task for this pull request at https://phabricator.vyos.net ?
If no, please grab account and create one.
Thanks for contribution!

**Comment by dmbaturin** [comment]
I'm going to merge it right away, but yes, we need a task first. Not having a task makes it hard to make release notes later when we have so many submodules!

**Comment by nicko170** [comment]
I hope I have done this correctly :-)

https://phabricator.vyos.net/T545

**Comment by andamasov** [comment]
Yes, perfect
Thank you!

**Comment by dmbaturin** [comment]
The full policy is to reference the task number in commits too (like "T545: fix IPv6 next-hop matching in route-maps", but for first time contributors we don't insist on it too hard.

**Comment by nicko170** [comment]
Thanks @dmbaturin  - I'll keep this all in mind for next time, and actually go read the policies before I go creating pull requests :-)

I guess I just wanted to make sure it got added so when I go to software upgrade my production routers, it doesn't break the config. Ha.

I may also actually spin up a dev system, as there are heaps more things that I need to do still!

**Comment by dmbaturin** [comment]
@nicko170 Well, I wish github had any way to display the policy when someone makes a pull request. 

My only concern right now is whether FRR has the same issue with IPv4 and IPv6 next hop matching CLI disparity or not. If it does not, things will get quite interesting for us, so we'll need to check.

What you've done would be a breaking change if that feature ever worked to begin with, and would require pretty serious backwards compatibility effort to be made. Since it works now, then if FRR forces us to change it again, that effort will have to be made when we migrate to it, and automatic config migration may be tricky,

**Comment by nicko170** [comment]
Having a look at the guide for FRR, it suggests this is going to be an issue moving forward with FRR - unless their documentation is incorrect.

[FRR Route-map Command](https://frrouting.org/user-guide/Route-Map-Match-Command.html#Route-Map-Match-Command)

> Route-map Command: match ip next-hop ipv4_addr
> Matches the specified ipv4_addr.

Oddly enough though, Cisco supports prefix-list on both v4 and v6.

```
Router(config-route-map)#match ip next-hop ?
   <1-99>       IP access-list number
   <1300-1999>  IP access-list number (expanded range)
   WORD         IP standard access-list name
   prefix-list  Match entries of prefix-lists
   <cr>
 
 Router(config-route-map)#match ipv6 next-hop ?
   WORD         IPv6 access-list name
   prefix-list  IPv6 prefix-list
```

**Comment by dmbaturin** [comment]
Frankly, I've never used match ip next-hop and I don't understand what exactly is the use case for it. 

The most puzzling part to me is why it supports prefix-lists? Does it expect that every entry is /32? How it behaves with say a 192.0.2.0/24 le 27 rule?

**Comment by nicko170** [comment]
So - without going into too much detail, my use case is:

1. Using Vyos for Edge Routers
2. Each edge router peers with core switching layer over ospf and ospfv3
3. Not all devices (switches run ospf and mpls only) BGP peer with each other
4. Route map is used to match routes being learnt from customer, and allow redistribution of customer routes from bgp into ospf (to reach all devices that dont peer BGP). I match on next-hop here as an added layer of protection to ensure full routing tables don't get leaked into the ospf table. That'd be bad.

The use of prefix lists is good - if a customer has multiple bgp speakers back to the edge, it's only a single entry in the redistribution route map, instead of an entry per speaker, per customer.

It's probably not the BEST design, however with the requirements that I have it's been working perfectly for ages - until it was a matter of setting up IPv6 in the same way then breaking the config engine.

**Comment by dmbaturin** [comment]
You mean, only redistribute to OSPF if the next-hop is one of your eBGP peers? I don't see how it protects from full table leaks — if your peer leaks its full table to you, it will be redistributed to OSPF. I guess we are sidetracking this into a design discussion, but my opinion is that a downstream or equal peering session without a list of allowed prefixes or at least maximum prefix limit is a full feed leak waiting to happen. ;)

Also, you didn't answer the second question. What is intended behaviour when prefix-list rule is not a /32? Will it match all next-hops that belong to that network?

**Comment by nicko170** [comment]
> You mean, only redistribute to OSPF if the next-hop is one of your eBGP peers? I don't see how it protects from full table leaks — if your peer leaks its full table to you, it will be redistributed to OSPF. I guess we are sidetracking this into a design discussion, but my opinion is that a downstream or equal peering session without a list of allowed prefixes or at least maximum prefix limit is a full feed leak waiting to happen. ;)

Absolutely not - import prefix lists per downstream peer, communities AND next-hop checking are all enabled for this :-). The example I posted was stripped to basics for the purpose of the bug/ticket/feature - But back away from the network design topic now, as yeah - it's sidetracked. I just wanted to provide an example use case that works for me :-)

> Also, you didn't answer the second question. What is intended behaviour when prefix-list rule is not a /32? Will it match all next-hops that belong to that network?

I am not sure at this stage, I'd imagine Quagga would fail to to match any routes with the route-map. My curiosity is going to kill me here unless I test it, so stand by - I'll spin up two boxes when I get home and test. Cannot really justify $work time on _that_ question :-)

**Pull request merged**
