### PR TITLE
Added IPv4 in description to distinct from IPv6 BGP configuration.

### PR DESCRIPTION
**Pull request by wornet-mwo**
I had problems configuring IPv6-BGP correctly as the descriptions did not clarify what is used for ipv4 only.

This PR mentions IPv4 at each setting in it's description at least as a hint.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Good point!

**Comment by dmbaturin** [comment]
@wornet-mwo Thanks for the contribution! Our standard procedure is to first create a task in https://phabricator.vyos.net , then reference its number in commit messages as in "T123: Add distinct help strings for IPv4 and IPv6 BGP" so that phabricator picks them up. Otherwise tracking changes across multiple packages is too hard.

We usually lift this requirement for first time contributors especially if the change is small, please remember to follow that process next time.

**Comment by wornet-mwo** [comment]
@dmbaturin Thanks for this information, i thought this is done automatically. I'll do next time.

**Comment by dmbaturin** [comment]
No, since github issues are limited to a single repo, there's simply no way to track issues across multiple repos, so it has to be done externally, but without an explicit task reference, external tools can't know which task to associate a commit with.

**Pull request merged**
