### PR TITLE
bgp: T2100:Bgp route advertisement with rib checks

### PR DESCRIPTION
**Pull request by sever-sever**
Add option enable-network-import-check for bgp.
Enable IGP route check for network statements

### CODE REVIEW

**Comment by jestabro** [comment]
@sever-sever I would suggest naming the parameter 'network-import-check', instead of 'enable-network-import-check', but other than that, it all works nicely.

**Comment by sever-sever** [comment]
> @sever-sever I would suggest naming the parameter 'network-import-check', instead of 'enable-network-import-check', but other than that, it all works nicely.

Fixed

**Comment by sever-sever** [comment]
@jestabro Fixed

**Review by c-po — CHANGES_REQUESTED** [review]
Unfortunately its still named "enable-network-import-check"

**Comment by c-po** [comment]
... shouldn't that be "default" behavior? If I remember correctly thats what e.g. Cisco does.

**Comment by jestabro** [comment]
@c-po see discussion in task T2100; I believe that @sever-sever may have a follow-up, from PM, but his position had been that it was dangerous to switch to the profile that has it as default. If we choose the (modified) PR as fix, I will add migration script.

**Comment by sever-sever** [comment]
> ... shouldn't that be "default" behavior? If I remember correctly thats what e.g. Cisco does.

@c-po it's not safe, https://phabricator.vyos.net/T2100#57387

**Comment by jestabro** [comment]
As @c-po points out, the node.def is still named:
 templates/protocols/bgp/node.tag/parameters/enable-network-import-check/node.def

**Comment by sever-sever** [comment]
> Unfortunately its still named "enable-network-import-check"
@jestabro gotcha you.
@cpo Fixed.

**Pull request merged**
