### PR TITLE
T1513: EVPN: Add abillity to configure frr L2VPN EVPN.

### PR DESCRIPTION
**Pull request by runborg**
This commit is a pre-release of adding basics L2VPN EVPN support in BGP.
It does only contain the simplest commands possible for establishing a L2vpn evpn relationship

### CODE REVIEW

**Comment by c-po** [comment]
> We only accept bugfixes in packages other than https://github.com/vyos/vyos-1x as no new functionality should use the old style templates (node.def and Perl/BASH code. Use the new style XML/Python interface instead.

Unfortunately I did not find the blog post only the wiki and the docs stement, why not use this opportunity on a BGP XML/Python implementation?

**Comment by ErmakovDmitriy** [comment]
> > We only accept bugfixes in packages other than https://github.com/vyos/vyos-1x as no new functionality should use the old style templates (node.def and Perl/BASH code. Use the new style XML/Python interface instead.
> 
> Unfortunately I did not find the blog post only the wiki and the docs stement, why not use this opportunity on a BGP XML/Python implementation?

Hi @c-po,

Could you tell me, please, if there is already FRR/Quagga configuration interface which uses Python/XML?

I tried to find the Python implementation in vyos-1x but I could not.

**Comment by c-po** [comment]
@ErmakovDmitriy bfd or pim are already done via XML/Python

**Comment by c-po** [comment]
Now with BGP beeing implemented in the new style, this can be migrated over so it will make it into VyOS 1.4 for testing.

**Comment by c-po** [comment]
Superseeded by https://github.com/vyos/vyos-1x/pull/724

**Pull request closed without merging**
